server:
  port: 8130

eureka:
  client:
    service-url:
      defaultZone:  http://47.106.212.169:8761/eureka/
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    #instance-id: ${spring.application.name}-${eureka.instance.ip-address}:${server.port}
  healthcheck:
    enabled: true

feign:
  hystrix:
    enabled: true

spring:
      #环境dev，pro 用于配置获取
  profiles:
    active: dev

  redisson:
    database: 0
    password: derrick
    timeout: 3000
  #sentinel/cluster/single
    mode: single
  #连接池配置
    pool:
      max-idle: 16
      min-idle: 8
      max-active: 8
      max-wait: 3000
      conn-timeout: 3000
      so-timeout: 3000
      size: 10
  #单机配置
    single:
      address: 47.106.212.169:6379
  #redis
  redis:
    host: 47.106.212.169
    password: derrick
    port: 6379

  application:
    name: frame-blog
sharding.jdbc:
 data-sources:
     ds_master:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://47.106.212.169:3306/frame-blog-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
       username: root
       password: root
       max-active: 8
       max-wait: 60000
       initial-size: 1
       min-idle: 1
     ds_slave_0:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://47.106.212.169:3307/frame-blog-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
       username: slave
       password: slave
 master-slave-rule:
    name: ds_ms
    master-data-source-name: ds_master
    slave-data-source-names: ds_slave_0
    load-balance-algorithm-type: round_robin



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.frame.user.web.entity
  global-config:
    #refresh: true
    db-config:
      column-like : true
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      #id-type: 1
      #驼峰下划线转换
      db-column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
      #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
#日志配置文件
logging:
  config: classpath:logConfig/logback-dev.xml

#xxl-job
xxl-job:
    adminAddress: http://47.106.212.169:8190/xxl-job-admin
    #adminAddress: http://127.0.0.1:8190/xxl-job-admin
    accessToken:
    executor:
      appname: ${spring.application.name}
      port: 18110
      ip:
      logpath: /Users/lemonade/code/logs/
      logretentiondays: -1


